name: Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
